apiVersion: v1
kind: Pod
metadata:
  name: secure-webserver
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 100
    runAsGroup: 102
  containers:
  - name: webserver
    image: bv344/my-webserver:v3
    ports:
    - containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
        - ALL
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
